CREATE TABLE IF NOT EXISTS profiles(
  id TEXT PRIMARY KEY, username TEXT UNIQUE NOT NULL, full_name TEXT NOT NULL DEFAULT '',
  email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'user',
  bio TEXT NOT NULL DEFAULT '', avatar_url TEXT NOT NULL DEFAULT '',
  is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS categories(id TEXT PRIMARY KEY,name TEXT UNIQUE NOT NULL,icon TEXT NOT NULL DEFAULT '📚',created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS skills(
  id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,category_id TEXT REFERENCES categories(id) ON DELETE SET NULL,
  level TEXT NOT NULL DEFAULT 'Beginner',description TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS exchange_requests(
  id TEXT PRIMARY KEY,sender_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  receiver_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  skill_to_learn_id TEXT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
  skill_offered_id TEXT REFERENCES skills(id) ON DELETE SET NULL,message TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions(
  id TEXT PRIMARY KEY,request_id TEXT REFERENCES exchange_requests(id) ON DELETE SET NULL,
  requester_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  teacher_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  skill_id TEXT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
  date TEXT NOT NULL,time TEXT NOT NULL,duration INTEGER NOT NULL DEFAULT 60,
  mode TEXT NOT NULL DEFAULT 'Online',notes TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'upcoming',created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS messages(
  id TEXT PRIMARY KEY,sender_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  receiver_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,content TEXT NOT NULL,
  read BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS reviews(
  id TEXT PRIMARY KEY,reviewer_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  reviewed_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
  skill_id TEXT REFERENCES skills(id) ON DELETE SET NULL,rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),
  review TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS notifications(
  id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,type TEXT NOT NULL DEFAULT 'general',
  title TEXT NOT NULL DEFAULT '',message TEXT NOT NULL DEFAULT '',is_read BOOLEAN NOT NULL DEFAULT FALSE,
  related_id TEXT,created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ai_history(
  id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  feature TEXT NOT NULL,input_text TEXT NOT NULL DEFAULT '',output_text TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
